---
- name: Set up Plex Media Server
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Install Plex Media Server
      community.general.snap:
        name: plexmediaserver
        state: present
        classic: true
        channel: stable
