---

# TODO: Maybe only run this once, the very first time.
- name: Update apt packages
  ansible.builtin.apt:
    upgrade: true
    state: latest # I know the linter will complain, but I do NOT care. Let's have the latest, please.
    update_cache: true
    cache_valid_time: 3600

- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    update_cache: true
    cache_valid_time: 3600

- name: Install very basics
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - zsh
