---
roles:

  - name: gothick.awscli
    src: https://github.com/gothick/ansible-awscli.git

  - name: gothick.ghostty
    src: https://github.com/gothick/ansible-ghostty.git

  - name: Oefenweb.postfix
    version: "v3.7.6"

  - name: geerlingguy.pip
    version: "3.0.3"

  - name: geerlingguy.firewall
    version: "2.5.1"

  # TODO Replace with a role that can install Java 18; this seems to max out at 17.
  - name: geerlingguy.java
    version: "2.5.2"

collections:
  - name: hifis.toolkit
    version: "5.3.0"
