---
- name: Install Samba
  hosts: all
  become: true

  # vars_files:
  #   - vars.yml

  tasks:
    - name: Install Samba
      ansible.builtin.apt:
        name: samba
        state: present
        update_cache: true
        cache_valid_time: 3600

    # - name: Create a directory for shared files
    #   ansible.builtin.file: