---
- name: Install VS Code
  hosts: all
  become: true

  # vars_files:
  #   - vars.yml

  tasks:
    - name: Install Visual Studio code via Snap
      community.general.snap:
        name: code
        state: present
        classic: yes
        channel: stable
