---
- name: Install ansible

  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - ansible
      - ansible-lint # Useful for Visual Studio Ansible plugin, etc.
      - python3-boto3 # Required for aws/ec2 ansible plugins
      - python3-botocore # Required for aws/ec2 ansible plugins
      - cowsay # Because who *doesn't* want a talking cow?

- name: Create Ansible developer user
  ansible.builtin.user:
    name: "{{ ansible_developer_user }}"
    state: present
    groups: sudo
    append: true
    create_home: true
  register: user_info

- name: Add user to passwordless sudoers
  ansible.builtin.template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ ansible_developer_user }}"
    mode: "0644"

- name: Add authorised key so I can log in as the developer user from my Mac
  ansible.posix.authorized_key:
    user: "{{ ansible_developer_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ ansible_authorised_keys }}"

- name: Set ssh dir
  ansible.builtin.set_fact:
    ssh_dir: "{{ user_info.home }}/.ssh"

- name: Ensure .ssh directory present
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ ansible_developer_user }}"
    group: "{{ ansible_developer_user }}"

- name: Create public key file for Ansible's user
  ansible.builtin.template:
    src: ansible.pub.j2
    dest: "{{ ssh_dir }}/ansible.pub"
    owner: "{{ ansible_developer_user }}"
    group: "{{ ansible_developer_user }}"
    mode: '0644'

- name: Create private key file for Ansible's user
  ansible.builtin.template:
    src: ansible.j2
    dest: "{{ ssh_dir }}/ansible"
    owner: "{{ ansible_developer_user }}"
    group: "{{ ansible_developer_user }}"
    mode: '0600'
